### PR TITLE
Fix config

### PR DESCRIPTION
**Pull request by thomasstephane**
Reset the DB to structure.sql
Fix the config for Spotify so tests don't need it.

### CODE REVIEW

**Review by jmarsh24 — COMMENTED** [review]
This file consolidation is causing problems when pushing to Heroku. Running rails db:migrate results in duplication conflicts which cause the migration to fail.

**Review by jmarsh24 — COMMENTED** [review]
Is it necessary to consolidate all the migrations in this manner?

**Comment by thomasstephane** [comment]
Your migrations are currently broken, so yes. that or you need to repair them one at a time. but the error on Heroku doesn't appear to be this, but rather some postgresql permission of some sort. What is it saying?

**Comment by jmarsh24** [comment]
I think I fixed the permissions error. I just removed the migration from the initialize schema file. I read online that some people have trouble installing them through rails and that it can be better to just installed them using heroku pg:psql. 

I installed these extensions for Postgres quite early in my migrations and all these migrations seemed to be working before we merged them into this initialize schema file. The formatting I guess has changed to structure.sql.

I'm having a hard time to understand what is actually wrong. It's trying to create tables that already exist, which makes me think that we just need to add "if not exists, migrate this table for everything".

On the local db level, everything seems to migrate just fine.

Here is a the error that I receive from heroku.

https://gist.github.com/jmarsh24/bf11accd4e328a3867b9632e01ac5c34

Would it be easier for me to just give you access to the heroku server so you could try pushing to it directly?

**Pull request merged**
